version: 2.1
orbs:
  ruby: circleci/ruby@2.0.1
  codecov: codecov/codecov@4.0.1
jobs:
  test-ruby:
    # Install gems, run tests
    docker:
      - image: cimg/ruby:3.2-node
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: rspec test
          command: bundle exec rspec
workflows:
  build-and-test:
    jobs:
      - test-ruby
  upload-to-codecov:
    jobs:
      - checkout
      - codecov/upload
